import fs from "fs";
import path from "path";
import { fetchBuckets } from "./fetchBuckets.js";

const allBuckets = [];

async function preloadAllBuckets() {
  let offset = 0;
  const limit = 100;
  let moreExist = true;

  while (moreExist) {
    const { buckets, moreExist: hasMore } = await fetchBuckets(
      offset,
      "",
      limit
    );
    allBuckets.push(...buckets);
    offset += limit;
    moreExist = hasMore;
  }

  const jsModuleString = `// Auto-generated by preloadBuckets.js
export const bucketsData = ${JSON.stringify(
    { updatedAt: Date.now(), buckets: allBuckets },
    null,
    2
  )};
`;

  fs.writeFileSync(path.resolve("./bucketsData.js"), jsModuleString);
  console.log("✅ Buckets saved as bucketsData.js");
}

preloadAllBuckets();
